#!/bin/bash

echo "GitHub Push Helper for Ecospatial Website"
echo "========================================"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. First, make sure you have created a new Personal Access Token with 'repo' permissions:"
echo "   Go to: https://github.com/settings/tokens/new"
echo "   - Name: 'Ecospatial Push'"
echo "   - Expiration: 30 days (or your preference)"
echo "   - Scopes: Select 'repo' (all checkboxes under repo)"
echo "   - Click 'Generate token'"
echo "   - Copy the token that starts with 'ghp_'"
echo ""
echo "2. Run these commands one by one:"
echo ""
echo "   cd /Users/misocho/Playground/waweru/ecospatial-website"
echo "   git remote remove origin"
echo "   git remote add origin https://github.com/wawer448/Afriafri.git"
echo "   git push -u origin main"
echo ""
echo "3. When prompted:"
echo "   - Username: wawer448"
echo "   - Password: [Paste your new token here]"
echo ""
echo "Alternative: Upload files manually"
echo "================================="
echo "1. Go to: https://github.com/wawer448/Afriafri"
echo "2. Click 'Add file' > 'Upload files'"
echo "3. Drag these folders/files:"
echo "   - css/"
echo "   - js/"
echo "   - index.html"
echo "   - README.md"
echo "4. Commit the changes"
echo ""
echo "After uploading, enable GitHub Pages:"
echo "1. Go to Settings > Pages"
echo "2. Source: Deploy from a branch"
echo "3. Branch: main, folder: / (root)"
echo "4. Save"
echo ""
echo "Your site will be at: https://wawer448.github.io/Afriafri/"